apiVersion: v1
kind: Service
metadata:
  name: {{ include "chirpstack.core" . }}
  labels:
    {{- include "chirpstack.labels" . | nindent 4 }}
  {{- with .Values.chirpstack.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.chirpstack.service.type }}
  {{- with .Values.chirpstack.service.spec }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
  ports:
    - port: {{ .Values.chirpstack.http.port }}
      targetPort: {{ .Values.chirpstack.http.containerPort }}
      protocol: TCP
      name: dashboard
    {{- if .Values.chirpstack.metrics.enabled }}
    - port: {{ .Values.chirpstack.metrics.port }}
      targetPort: {{ .Values.chirpstack.metrics.containerPort }}
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "chirpstack.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: core
