apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: mosquitto
  name: mosquitto
  namespace: chirpstack
spec:
  type: ClusterIP
  ports:
  - name: "8883"
    port: 8883
    targetPort: 8883
  selector:
    io.kompose.service: mosquitto
status:
  loadBalancer: {}
